fix: update APK file path selection based on environment in Firebase App Distribution workflow

diff --git a/.github/workflows/Upload To Firebase App Distribution.yml b/.github/workflows/Upload To Firebase App Distribution.yml
--- a/.github/workflows/Upload To Firebase App Distribution.yml
+++ b/.github/workflows/Upload To Firebase App Distribution.yml
@@ -75,4 +75,12 @@ jobs:
           appId: ${{secrets.FIREBASE_APP_ID}}
           serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
           groups: testers
-          file: ${{ steps.build.outputs.apk_path }}
+          file: |
+            if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
+              echo "app/build/outputs/apk/debug/app-debug.apk"
+            elif [[ "${{ github.event.inputs.environment }}" == "release" ]]; then
+              echo "app/build/outputs/apk/release/app-release.apk"
+            else
+              echo "Invalid environment selected"
+              exit 1
+            fi
